type Query {
  books: [Book]
  library: [Library]
  favoriteColor: AllowedColor
  commonVulnType: VulnType
  colors: ColorHex
}

type Book {
  title: String
  author: String
}

# type-level的maxAge，field自动继承
# Query.field-level的maxAge，field 不 继承。所以需要显式声明所有字段
type Library @cacheControl(maxAge: 5) {
  name: String #@cacheControl(inheritMaxAge: true)
  books: [Book] @cacheControl(maxAge: 3)
}

type EnabledColor implements ColorHex {
  hex: String
  enabled: Boolean
}
type DisabledColor implements ColorHex {
  hex: String
  disabled: Boolean
}

union AllColor = EnabledColor | DisabledColor
interface ColorHex {
  hex: String
}
