type Query {
  books: [Book]
  library(country: String): [Library]
  favoriteColor: AllowedColor
  commonVulnType: VulnType
  colors: ColorHex
}

type Book @cacheControl(maxAge: 30) {
  title: String
  author: String
}

# type-level的maxAge，field自动继承
# Query.field-level的maxAge，field 不 继承。所以需要显式声明所有字段
type Library @cacheControl(maxAge: 5) {
  name: String #@cacheControl(inheritMaxAge: true)
  books: [Book]
}

type EnabledColor implements ColorHex {
  hex: String
  enabled: Boolean
}
type DisabledColor implements ColorHex {
  hex: String
  disabled: Boolean
}

union AllColor = EnabledColor | DisabledColor
interface ColorHex {
  hex: String
}
